name: Sync with S3

on:
  push:
    branches:
      - main
      - test-size-only

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y git-restore-mtime
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls -al --full-time
      - run: ls -al --full-time json-docs/ember/3.9.1/classes
      - run: git restore-mtime
      - run: ls -al --full-time
      - run: ls -al --full-time json-docs/ember/3.9.1/classes
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: >-
            --acl public-read
            --follow-symlinks
            --exclude '.git/*'
            --exclude '.github/*'
            --exclude '.gitignore'
            --exclude 'README.md'
        env:
          AWS_S3_BUCKET: ember-api-docs-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
